# Site
name: husyn.dev
title: husyn.dev
logo: "assets/images/favicon.ico"
favicon: 'assets/images/favicon.ico'
email: info@husyn.dev
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog in which I'll write about my YouTube videos, philosophies I have about Software Enginenering, Computer Science and Modern Application Development in general. 
  I love AWS Cloud and want others to understand the power of true Agile mindset.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://husyn.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: husynraj
github_username:  husyn
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
# Authors
authors:
  husyn:
    name: Hussain Mansoor
    site: https://husyn.dev
    bio: "Certified AWS Architect & Developer with MS in Software Engineering. Working on Cloud & Agile for more than 10 years."
    display_name: Husyn
    avatar: "assets/images/avatar.png"
    gravatar: 9e461722a08efe3834ec576fcd328089
    email: info@husyn.dev
    web: https://husyn.dev
    twitter: https://twitter.com/husynraj
    twitterHandle: husynraj
    description: "A computer scientist with philosophical Software Engineering passion"
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: husyn
      avatar: /assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
