name: husyn.dev
title: husyn.dev
logo: "assets/images/favicon.ico"
email: hussain@manshur.solutions
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog in which I'll write about my YouTube videos, philosophies I have about Software Enginenering, Computer Science and Modern Application Development in general. 
  I love AWS Cloud and want others to understand the power of true Agile mindset.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://husyn.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: husynraj
github_username:  husyn

# Build settings
theme: minima
whitelist: [jekyll-analytics]
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-seo-tag

jekyll_analytics:
  GoogleAnalytics:
    id: UA-186027956-1
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

exclude:
#   - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Authors
authors:
  husyn:
    name: Husyn
    display_name: Husyn
    avatar: "assets/images/avatar.png"
    gravatar: 9e461722a08efe3834ec576fcd328089
    email: hussain@manshur.solutions
    web: https://husyn.dev
    twitter: https://twitter.com/husynraj
    twitterHandle: husynraj
    description: "A computer scientist with philosophical Software Engineering passion"